/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.flurry.avroserver.protocol.v1;  
@SuppressWarnings("all")
public class AdRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdRequest\",\"namespace\":\"com.flurry.avroserver.protocol.v1\",\"fields\":[{\"name\":\"adSpaceName\",\"type\":\"string\"},{\"name\":\"location\",\"type\":{\"type\":\"record\",\"name\":\"Location\",\"fields\":[{\"name\":\"lat\",\"type\":\"float\",\"default\":0.0},{\"name\":\"lon\",\"type\":\"float\",\"default\":0.0}]},\"default\":\"null\"}]}");
  @Deprecated public java.lang.CharSequence adSpaceName;
  @Deprecated public com.flurry.avroserver.protocol.v1.Location location;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return adSpaceName;
    case 1: return location;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: adSpaceName = (java.lang.CharSequence)value$; break;
    case 1: location = (com.flurry.avroserver.protocol.v1.Location)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'adSpaceName' field.
   */
  public java.lang.CharSequence getAdSpaceName() {
    return adSpaceName;
  }

  /**
   * Sets the value of the 'adSpaceName' field.
   * @param value the value to set.
   */
  public void setAdSpaceName(java.lang.CharSequence value) {
    this.adSpaceName = value;
  }

  /**
   * Gets the value of the 'location' field.
   */
  public com.flurry.avroserver.protocol.v1.Location getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(com.flurry.avroserver.protocol.v1.Location value) {
    this.location = value;
  }

  /** Creates a new AdRequest RecordBuilder */
  public static com.flurry.avroserver.protocol.v1.AdRequest.Builder newBuilder() {
    return new com.flurry.avroserver.protocol.v1.AdRequest.Builder();
  }
  
  /** Creates a new AdRequest RecordBuilder by copying an existing Builder */
  public static com.flurry.avroserver.protocol.v1.AdRequest.Builder newBuilder(com.flurry.avroserver.protocol.v1.AdRequest.Builder other) {
    return new com.flurry.avroserver.protocol.v1.AdRequest.Builder(other);
  }
  
  /** Creates a new AdRequest RecordBuilder by copying an existing AdRequest instance */
  public static com.flurry.avroserver.protocol.v1.AdRequest.Builder newBuilder(com.flurry.avroserver.protocol.v1.AdRequest other) {
    return new com.flurry.avroserver.protocol.v1.AdRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for AdRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdRequest>
    implements org.apache.avro.data.RecordBuilder<AdRequest> {

    private java.lang.CharSequence adSpaceName;
    private com.flurry.avroserver.protocol.v1.Location location;

    /** Creates a new Builder */
    private Builder() {
      super(com.flurry.avroserver.protocol.v1.AdRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.flurry.avroserver.protocol.v1.AdRequest.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing AdRequest instance */
    private Builder(com.flurry.avroserver.protocol.v1.AdRequest other) {
            super(com.flurry.avroserver.protocol.v1.AdRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.adSpaceName)) {
        this.adSpaceName = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.adSpaceName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.location)) {
        this.location = (com.flurry.avroserver.protocol.v1.Location) data().deepCopy(fields()[1].schema(), other.location);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'adSpaceName' field */
    public java.lang.CharSequence getAdSpaceName() {
      return adSpaceName;
    }
    
    /** Sets the value of the 'adSpaceName' field */
    public com.flurry.avroserver.protocol.v1.AdRequest.Builder setAdSpaceName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.adSpaceName = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'adSpaceName' field has been set */
    public boolean hasAdSpaceName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'adSpaceName' field */
    public com.flurry.avroserver.protocol.v1.AdRequest.Builder clearAdSpaceName() {
      adSpaceName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'location' field */
    public com.flurry.avroserver.protocol.v1.Location getLocation() {
      return location;
    }
    
    /** Sets the value of the 'location' field */
    public com.flurry.avroserver.protocol.v1.AdRequest.Builder setLocation(com.flurry.avroserver.protocol.v1.Location value) {
      validate(fields()[1], value);
      this.location = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'location' field has been set */
    public boolean hasLocation() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'location' field */
    public com.flurry.avroserver.protocol.v1.AdRequest.Builder clearLocation() {
      location = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AdRequest build() {
      try {
        AdRequest record = new AdRequest();
        record.adSpaceName = fieldSetFlags()[0] ? this.adSpaceName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.location = fieldSetFlags()[1] ? this.location : (com.flurry.avroserver.protocol.v1.Location) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
